### ISSUE TITLE
项目会不断演进，欢迎关注

### ISSUE THREAD

**Issue by halower** [halower/vue2-tree#1]

**Comment by xCc0824MM** [comment]
刚接触vue没几天  使用还不是特熟练   github上的项目能跑起来，但是不知道怎么应用到自己的项目中，其他的tree插件直接vue.use(...)   希望能写个教程怎么移植到自己的项目

**Comment by halower** [comment]
你把那个components文件夹考到你的项目中，同时如果需要那就个小图标就拷下图片，然后按照实例引入就可以。
你说的那种事发布到npm上的，我没有推上去。后面有时间我就推到npm上去

**Comment by emorlasar** [comment]
数据现在是不是不能异步加载？数据量大了会卡。 能结合vuex用吗？

**Comment by halower** [comment]
@emorlasar 是的，暂时没有支持异步加载，大概一个月左右才会进行一些特性的扩展，暂时没有时间处理这个组件

**Comment by topwood** [comment]
在初始化的时候就新建一个store用来存储数据，导致了不能做数据绑定
