### ISSUE TITLE
怎么应用在自己的项目里

### ISSUE THREAD

**Issue by xCc0824MM** [halower/vue2-tree#2]
刚接触vue没几天 使用还不是特熟练 github上的项目能跑起来，但是不知道怎么应用到自己的项目中，其他的tree插件直接vue.use(...) 希望能写个教程怎么移植到自己的项目

**Comment by halower** [comment]
你把那个components文件夹考到你的项目中，同时如果需要那就个小图标就拷下图片，然后按照实例引入就可以。
你说的那种事发布到npm上的，我没有推上去。后面有时间我就推到npm上去

**Comment by halower** [comment]
# #
