### ISSUE TITLE
关于父子节点选中的状态，觉得逻辑有点问题

### ISSUE THREAD

**Issue by Klay-Clam** [halower/vue2-tree#39]
1.  子节点全选，但是父节点没有被选中
2.  我觉得子节点只要被选中一个，父节点状态应该是至少是半选的状态

**Comment by halower** [comment]
这个问题可能是这几天合并代码搞出来的，你可以看看新版本：https://github.com/halower/vue2-tree/tree/develop，也快开发完了，效率提升了不少

**Comment by Klay-Clam** [comment]
好的，谢谢
